name: 'Helloworld Action'
description: 'Executes a PowerShell script with parameters'
inputs:
  projectName:
    description: 'The name of the project'
    required: true
  simulateFail:
    description: 'Set to true to simulate a failure in the script'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - run: |
        powershell -File ${{ github.workspace }}/helloworld-script.ps1 -projectName ${{ inputs.projectName }} -simulateFail ${{ inputs.simulateFail }}
      shell: pwsh
