name: "Helloworld Action"
description: "Executes a PowerShell script with parameters"
inputs:
  projectName:
    description: "The name of the project"
    required: true
  simulateFail:
    description: "Set to true to simulate a failure in the script"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - run: |
        echo "HELLOWORLD_PROJECT_NAME=${{ inputs.projectName }}" >> $GITHUB_ENV
        echo "HELLOWORLD_SIMULATE_FAIL=${{ inputs.simulateFail }}" >> $GITHUB_ENV
      shell: bash
    - run: |
        powershell -File ${{ github.action_path }}/scripts/helloworld-script.ps1
      shell: powershell
