param (
    [string]$projectName,
    [string]$simulateFail
)

# Print received parameters for logging
Write-Host "Helloworld Running"
Write-Host "Received parameters:"
Write-Host "Project Name: $projectName"
Write-Host "Simulate Fail: $simulateFail"

# Try-Catch block for error handling
try {
    # Echo the project name
    Write-Host "The project name is: $projectName"

    # Your logic here...

    # Generating an artifact
    $artifactContent = "This is a test artifact generated by PowerShell for project $projectName."
    $artifactContent | Out-File "artifact.txt"

    # Generating output for logging
    Write-Host "Artifact created successfully for $projectName."

    # Simulating a failure
    if ($simulateFail -eq "true") {
        throw "Simulated failure triggered."
    }
}
catch {
    # Catching and displaying the error
    Write-Host "Error: $_"
    exit 1
}

# Successful execution
Write-Host "PowerShell script executed successfully."
exit 0
